services:
  web:
    build: .
    links: 
     - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
     - ./db:/data/db
    restart: always
    ports:
      - "27017:27017"
        
  nginx:
    image: nginx
    ports:
     - "80:80"
    restart: always
    links: 
     - web
    volumes: 
     - ./default.conf:/etc/nginx/conf.d/default.conf
